auto: true

markdown: kramdown
pygments: true
paginate: 10
paginate_path: "page:num"
permalink: pretty

title: 技术人生
baseurl: /
url: http://sixloop.cf
feed: /atom.xml
author_info: <a href="http://github.com/zhouchangxun">github</a>

highlighter: rouge
